In [1]:
import numpy as np

In [2]:
#Упражнение 1
q=np.array([1, 2, 3])
w=np.array([4, 5, 6])
E=np.dot(q,w)
print(E)
print(np.inner(q,w))

32
32


In [3]:
#Упражнение 2
q=np.array([[1, 2, 3], [4, 5, 6]])
w=np.array([[1, 2], [3, 4], [5, 6]])
print(np.dot(q, w))
print(np.matmul(q, w))
e=np.eye(3)
print(np.dot(q, e))

[[22 28]
 [49 64]]
[[22 28]
 [49 64]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
#Упражнение 3
q=np.array([[1, 2, 3], [4, 5, 6]])
print(np.linalg.norm(q))

9.539392014169456


In [15]:
#Упражнение 4
q=np.array([1, 2, 4])
w=np.array([3, 5, 6])
e=np.inner(q, w)
r=np.linalg.norm(q)*np.linalg.norm(w)
print(e/r)

0.9650349822710069


In [21]:
#Упражнение 5
q=np.array([[1, 2], [4, 5]])
w=q.T
print(np.linalg.det(q)) 
print(np.linalg.det(w))
e=np.array([[0, 0,], [4,5]])
print(np.linalg.det(e))
Q=np.array([[4, 5], [1, 2]])
print(np.linalg.det(Q))
R=np.array(([3, 3], [3, 3]))
print(np.linalg.det(R))
A=np.array([[5,10],[4, 5]])
print(np.linalg.det(A))
S=np.array([[21,27], [4, 5]])
print(np.linalg.det(S))

-2.9999999999999996
-2.9999999999999996
0.0
2.9999999999999996
0.0
-15.0
-2.99999999999999
